### ISSUE TITLE
HM3/16: Потерял кое-что

### ISSUE THREAD

**Issue by askerka** [AlexanderdeI/TMS#18]
Если словарь такой: {'l': 1, 'k': 1}, то какой максимальный элемент будет, после преобразований в твоём коде?

**Comment by AlexanderdeI** [comment]
Исправил

**Comment by askerka** [comment]
Зачем словарь инвертировать?
Если ты инвертировал словарь для поиска, зачем ты используешь тогда в конце цикл? Можно же просто взять значение.
