### ISSUE TITLE
HM4/16: Лишняя проверка first_num < second_num

### ISSUE THREAD

**Issue by askerka** [AlexanderdeI/TMS#34]
Проверка лишняя, так как 1 % 5 == 1. И ещё мелкие придирки:

- названия переменных могли бы подсказать или объяснить, что делает функция, но у тебя нет (можно было назвать как делимое и делитель, а вместо result - остаток)
- длинные названия, хотя вроде бы ок, но можно чуть короче

**Comment by AlexanderdeI** [comment]
Убрал проверку, переименовал переменные
